# Generated by Django 6.1.1 on 2026-09-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("urlapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="alias",
            field=models.CharField(max_length=20),
        ),
    ]
