# Generated by Django 6.1.1 on 2026-09-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("urlapi", "0002_alter_url_alias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="address",
            field=models.CharField(max_length=16384),
        ),
        migrations.AlterField(
            model_name="url",
            name="alias",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
