# Generated by Django 6.1.1 on 2026-09-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapi', '0003_alter_url_address_alter_url_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='address',
            field=models.URLField(max_length=16384),
        ),
    ]
